// Generated by scripts/generate-api-contract.mjs; do not edit.
import Foundation

enum LisaAPIContract {
    static let supportedMajorVersion = 1
    static let versionHeader = "X-Lisa-API-Version"
}
